### ISSUE TITLE
Problem with months

### ISSUE THREAD

**Issue by rodaguayo** [VeronicaNava/RiverLoad#3]
running the examples in CRAN presents the following error if you decide to disaggregate the information on a monthly (or yearly) basis

Error in aggrg.data[, i] <- agg.init[, 2] : 
  number of items to replace is not a multiple of replacement length

**Comment by VeronicaNava** [comment]
Which function has this issue? Thanks

**Comment by rodaguayo** [comment]
So far I have tried rating and fergunson functions, in both cases using the optional argument "period" presents the problem when aggregating the data. Thanks!

**Comment by VeronicaNava** [comment]
I run the examples (for ferguson and rating function) and I didn't encounter any problem. Can you please provide further details? are you using the db included in the package ("flow.data2" and "conc.data2") or any other dataset? Thanks!
